// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5D6RDe4eOMvRNkgbgXQqcYKGFxyuBQks',
    appId: '1:406378742477:web:ebee35dc4f9a648845df84',
    messagingSenderId: '406378742477',
    projectId: 'hostelapp-7ba6d',
    authDomain: 'hostelapp-7ba6d.firebaseapp.com',
    storageBucket: 'hostelapp-7ba6d.appspot.com',
    measurementId: 'G-91ECK7Y6NG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYV2RTxF1Z7AhQ8RtO4R-pRzpHScOpJF4',
    appId: '1:406378742477:android:7d16e8bd4a17e68645df84',
    messagingSenderId: '406378742477',
    projectId: 'hostelapp-7ba6d',
    storageBucket: 'hostelapp-7ba6d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBF0FoLxUutlt39GN6aoAFUSCuyUHTr0Fg',
    appId: '1:406378742477:ios:76de7d95d9c8a4f945df84',
    messagingSenderId: '406378742477',
    projectId: 'hostelapp-7ba6d',
    storageBucket: 'hostelapp-7ba6d.appspot.com',
    iosBundleId: 'com.example.hostelapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBF0FoLxUutlt39GN6aoAFUSCuyUHTr0Fg',
    appId: '1:406378742477:ios:76de7d95d9c8a4f945df84',
    messagingSenderId: '406378742477',
    projectId: 'hostelapp-7ba6d',
    storageBucket: 'hostelapp-7ba6d.appspot.com',
    iosBundleId: 'com.example.hostelapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5D6RDe4eOMvRNkgbgXQqcYKGFxyuBQks',
    appId: '1:406378742477:web:d913bbcdb2f064bd45df84',
    messagingSenderId: '406378742477',
    projectId: 'hostelapp-7ba6d',
    authDomain: 'hostelapp-7ba6d.firebaseapp.com',
    storageBucket: 'hostelapp-7ba6d.appspot.com',
    measurementId: 'G-Z52JYVLDHT',
  );
}
